config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :articles do
    member do
        put "like", to: "articles#upvote"
        put "dislike", to: "articles#downvote"
    end
  resources :comments
end
  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  acts_as_votable
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

before_action :authenticate_user!, except: [:index, :show]
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = current_user.articles.build
  end

  def edit
    @article = Article.find(params[:id])

  end

  def create
    @article = current_user.articles.build(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def upvote
    @article = Article.find(params[:id])
    @article.upvote_by(current_user)
    redirect_to request.referer
  end
  def downvote
    @article = Article.find(params[:id])
    @article.downvote_by(current_user)
    redirect_to request.referer
  end

  def update
    @article = Article.find(params[:id])
      if @article.update(article_params)
        redirect_to @article
      else
        if@article.user=current_user
        render 'edit'
      else
      @message = "It's not your comment wise guy :)"
      end
      redirect_to :back, notice: @message
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    @comment.user_id=current_user.id if current_user
    @comment.save
    if @comment.save
      redirect_to article_path(@article)
  else
    render 'new'
  end
end


  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(text)
    return '' unless text.present?
    @options ||= {
        autolink: true,
        fenced_code_blocks: true,
        underline: true,
        highlight: true,
        footnotes: true,
        tables: true,
        link_attributes: {rel: 'nofollow', target: "_blank"}
    }
    @markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML, @options)
    @markdown.render(text).html_safe
	end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for @article do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
      <%= f.label :title %><br>
      <%= f.text_area(:title, class: "form-control",style: 'width:30%;'  )%>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area( :text, class: "form-control", rows: 5 ) %>
    </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
	<div class="col-md-4">
		<div class="panel panel-default" >
			<div class="panel-heading" style=" height:90px; text-align:center; " >
                <h3><i class="fa fa-fw fa-gift"></i><%= article.title %></h3>
            </div>
            <div class="panel-body" style="  text-align:center;" >

							    <span class="label label-success label-as-badge"><%= article.get_upvotes.size %></span>
							    <span class="label label-danger label-as-badge"><%= article.get_downvotes.size %></span>

			<%= link_to "Show", article_path(article), class: "btn btn-default" %>
			<%if article.user==current_user %>
			<%= link_to "Edit", edit_article_path(article), class: "btn btn-default" %>
			<%= link_to "Destroy", article_path(article), method: :delete,
            data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
						<% end %>
			</div>
		</div>
	</div>
 <% end %>

app/views/articles/new.html.erb
<h1>New article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<h3><%= @article.title %></h3>
<%= markdown @article.text %>


<%= link_to like_article_path(@article), method: :put do %>
  <button type="button" class="btn btn-success" aria-label="Left Align">
    <span class="glyphicon.glyphicon-thumbs-up" aria-hidden="true"></span>
    <span class="badge"><%= @article.get_upvotes.size %></span>
  </button>
<% end %>
<%= link_to dislike_article_path(@article), method: :put do %>
  <button type="button" class="btn btn-danger" aria-label="Left Align">
    <span class="glyphicon.glyphicon-thumbs-down" aria-hidden="true"></span>
    <span class="badge"><%= @article.get_downvotes.size %></span>
  </button>
<% end %>
  Created by:
  <%= @article.user.email %>

  <p><%if @article.user==current_user %>
    <%= link_to 'Edit', edit_article_path(@article) , class: "btn btn-default" %>
  <% end %>
  <p>
<h3>Comments</h3>
<%= render @article.comments %>
<%if user_signed_in? %>
<h4>Add a comment:</h4>

<%= render 'comments/form' %>
<% end %>
<%= link_to 'Back', articles_path, class: "btn btn-default" %>

app/views/comments/_comment.html.erb
<b><%= comment.user.email %> says:</b> <%= comment.body %>


  <%if comment.user==current_user %>
  <%= link_to 'Delete', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
               <% end %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
<%if user_signed_in? %>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area( :body, class: "form-control",  ) %>
  </p>
  <p>

    <%= f.submit :class => "btn btn-default" %>
    <% end %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>



    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "Blog", articles_path, class: "navbar-brand" %>
                <%if !user_signed_in? %>
                  <%= link_to"Login", new_user_session_path, class: "navbar-brand" %>
                <% end %>

<%if user_signed_in? %>
    <%= link_to "New article", new_article_path, class: "navbar-brand" %>
    <%= link_to('Logout', destroy_user_session_path, :method => :delete, class: "navbar-brand") %>
<% end %>
            </div>

        </div>
    </nav>
<br/><br/>
    <!-- Page Content -->
    <div class="container">

        <!-- Marketing Icons Section -->
        <div class="row">
              <div class="col-lg-12">
                  <h1 class="page-header">
                      Blog
                  </h1>
              </div>

              <%= yield %>

        </div>


        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">

                </div>
            </div>
        </footer>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<h5>Witaj na moim blogu, miłego czytania<h5>